# Generated by Django 3.2 on 2023-03-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='recipe'),
        ),
    ]
